
export const CHECK_AUTH_STATUS='CHECK_AUTH_STATUS'

export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILURE='LOGIN_FAILURE'

export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAILURE='REGISTER_FAILURE'


export const NOTE_CREATED='NOTE_CREATED'
export const NOTE_CREATION_FAILED='NOTE_CREATION_FAILED'

export const FETCH_NOTES='FETCH_NOTES'
export const FETCH_NOTES_FAILED='FETCH_NOTES_FAILED'

export const UPDATE_NOTE='UPDATE_NOTE'
export const UPDATE_NOTE_FAILED='UPDATE_NOTE_FAILED'

export const DELETE_NOTE='UPDATE_NOTE'
export const DELETE_NOTE_FAILED='UPDATE_NOTE_FAILED'

export const  ADD_REMINDER='ADD_REMINDER'
export const  ADD_LABEL='ADD_LABEL'

